apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: istio-ambient
  namespace: flux-system
spec:
  interval: 1h0m0s
  type: oci
  url: oci://gcr.io/istio-release/charts
