apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-ztunnel
  namespace: flux-system
spec:
  interval: 1h0m0s
  chart:
    spec:
      chart: ztunnel
      version: 1.27.0
      sourceRef:
        kind: HelmRepository
        name: istio
  dependsOn:
  - name: istio-base
  - name: istio-cni
  install:
    createNamespace: false
    remediation:
      retries: 3
  targetNamespace: istio-system
  releaseName: istio-ztunnel
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
