apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-cni
  namespace: flux-system
spec:
  interval: 1h0m0s
  chart:
    spec:
      chart: cni
      version: 1.27.0
      sourceRef:
        kind: HelmRepository
        name: istio-ambient
  dependsOn:
  - name: istio-base
  install:
    createNamespace: false
    remediation:
      retries: 3
  targetNamespace: istio-system
  releaseName: istio-cni
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    profile: ambient
