apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace-istio-system.yaml
- helmrepository-istio.yaml
- helmrelease-istio-base.yaml
- helmrelease-istio-cni.yaml
- helmrelease-istio-ztunnel.yaml
- helmrelease-istio-istiod.yaml
