apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: gateway-api
  namespace: flux-system
spec:
  interval: 1h0m0s
  ref:
    tag: v1.4.0
  url: https://github.com/kubernetes-sigs/gateway-api
